*----------------------------------------------------------------------*
* Title: 
* Copyright (c) 2024 ProLogic LA S.C. All rights reserved
*----------------------------------------------------------------------*
* Project Rel. : Indumotora
* Author : Alberto Magaña
*----------------------------------------------------------------------*
* Program description:
* 
*----------------------------------------------------------------------*
interface ZIF_EWM_BASE_PARAM_C
  public .


  constants GC_ENH_GUI_MON_TU type ZEWM_DE_BASE_PARAMS_KEYENH value 'MON_TU' ##NO_TEXT.
  constants GC_ENH_WTCOWO001 type ZEWM_DE_BASE_PARAMS_KEYENH value 'WTCOWO001' ##NO_TEXT.
  constants GC_ENH_HUCRRE001 type ZEWM_DE_BASE_PARAMS_KEYENH value 'HUCRRE001' ##NO_TEXT.
  constants GC_ENH_IDOCS type ZEWM_DE_BASE_PARAMS_KEYENH value 'IDOCS' ##NO_TEXT.
  constants GC_ENH_GUI_REPL_BY_WAVE type ZEWM_DE_BASE_PARAMS_KEYENH value 'GUI_REPL_BY_WAVE' ##NO_TEXT.
  constants GC_ENH_PRINT_ACTA type ZEWM_DE_BASE_PARAMS_KEYENH value 'PRINT_ACTA' ##NO_TEXT.
  constants GC_ENH_RF_MAT_LBL type ZEWM_DE_BASE_PARAMS_KEYENH value 'RF_MAT_LBL_PRINT' ##NO_TEXT.
  constants GC_ENH_RF_NEEDPICK type ZEWM_DE_BASE_PARAMS_KEYENH value 'RF_NEEDPICK' ##NO_TEXT.
  constants GC_ENH_RF_PHY_INV type ZEWM_DE_BASE_PARAMS_KEYENH value 'RF_PHY_INV' ##NO_TEXT.
  constants GC_ENH_RF_PICK_CL type ZEWM_DE_BASE_PARAMS_KEYENH value 'RF_PICK_CL' ##NO_TEXT.
  constants GC_ENH_RF_PTHUSI type ZEWM_DE_BASE_PARAMS_KEYENH value 'RF_PTHUSI' ##NO_TEXT.
  constants GC_ENH_RF_REHU type ZEWM_DE_BASE_PARAMS_KEYENH value 'RF_REHU' ##NO_TEXT.
  constants GC_ENH_RF_TU type ZEWM_DE_BASE_PARAMS_KEYENH value 'RF_TU' ##NO_TEXT.
  constants GC_ENH_UNIT_WEIGHT type ZEWM_DE_BASE_PARAMS_KEYENH value 'UNIT_WEIGTH' ##NO_TEXT.
  constants GC_ENH_IN_MON_MD type ZEWM_DE_BASE_PARAMS_KEYENH value 'INMOMD' ##NO_TEXT.
  constants GC_PARAM_LGSYST type ZEWM_DE_BASE_PARAMS_KEYNAM value 'LGSYST' ##NO_TEXT.
  constants GC_PARAM_WCR type ZEWM_DE_BASE_PARAMS_KEYNAM value 'WCR' ##NO_TEXT.
  constants GC_PARAM_LGTYP type ZEWM_DE_BASE_PARAMS_KEYNAM value 'LGTYP' ##NO_TEXT.
  constants GC_PARAM_UOVOLUM type ZEWM_DE_BASE_PARAMS_KEYNAM value 'UOVOLUM' ##NO_TEXT.
  constants GC_PARAM_ALTUOM type ZEWM_DE_BASE_PARAMS_KEYNAM value 'ALTUOM' ##NO_TEXT.
  constants GC_FIELDNAME_STC type ABAP_COMPNAME value 'STC_' ##NO_TEXT.
  constants GC_PARAM_HNDLCODE type ZEWM_DE_BASE_PARAMS_KEYNAM value 'HNDLCODE' ##NO_TEXT.
  constants GC_PARAM_CALCU_BIN type ZEWM_DE_BASE_PARAMS_KEYNAM value 'CALCU_BIN' ##NO_TEXT.
  constants GC_PARAM_DEST_ST type ZEWM_DE_BASE_PARAMS_KEYNAM value 'DEST_ST' ##NO_TEXT.
  constants GC_PARAM_FILTER_PALLET type ZEWM_DE_BASE_PARAMS_KEYNAM value 'FILTER_PALLET' ##NO_TEXT.
  constants GC_PARAM_DOCTYPE_NEEDPICK type ZEWM_DE_BASE_PARAMS_KEYNAM value 'DOCTYPE_NEEDPICK' ##NO_TEXT.
  constants GC_PARAM_HU_CLOSE type ZEWM_DE_BASE_PARAMS_KEYNAM value 'HU_CLOSE' ##NO_TEXT.
  constants GC_PARAM_INVERSO_BIN type ZEWM_DE_BASE_PARAMS_KEYNAM value 'INVERSO_BIN' ##NO_TEXT.
  constants GC_PARAM_MTR_TU type ZEWM_DE_BASE_PARAMS_KEYNAM value 'MTR_TU' ##NO_TEXT.
  constants GC_PARAM_NUM_ITM type ZEWM_DE_BASE_PARAMS_KEYNAM value 'NUM_ITEM' ##NO_TEXT.
  constants GC_PARAM_PROCTY type ZEWM_DE_BASE_PARAMS_KEYNAM value 'PROCTY' ##NO_TEXT.
  constants GC_PARAM_PMAT type ZEWM_DE_BASE_PARAMS_KEYNAM value 'PMAT' ##NO_TEXT.
  constants GC_PARAM_PMAT_BINCONTAINER type ZEWM_DE_BASE_PARAMS_KEYNAM value 'BIN_CONT_VDLEWM02' ##NO_TEXT.
  constants GC_PARAM_PMAT_BIN_CONTAINER type ZEWM_DE_BASE_PARAMS_KEYNAM value 'BIN_CONTAINER' ##NO_TEXT.
  constants GC_PARAM_PMAT_PALLETCHEP type ZEWM_DE_BASE_PARAMS_KEYNAM value 'PALLET_CHEP_VDLEWM02' ##NO_TEXT.
  constants GC_PARAM_PMAT_PALLET_CHEP type ZEWM_DE_BASE_PARAMS_KEYNAM value 'PALLET_CHEP' ##NO_TEXT.
  constants GC_PARAM_QCLA_PHY_MUL type ZEWM_DE_BASE_PARAMS_KEYNAM value 'LGTYP_QCLA_PHY_MUL' ##NO_TEXT.
  constants GC_PARAM_STORAGE_PROC type ZEWM_DE_BASE_PARAMS_KEYNAM value 'STORAGE_PROC' ##NO_TEXT.
  constants GC_PARAM_ST_SUBSYST type ZEWM_DE_BASE_PARAMS_KEYNAM value 'ST_SUBSYST' ##NO_TEXT.
  constants GC_PARAM_TOTE_EXCEP type ZEWM_DE_BASE_PARAMS_KEYNAM value 'TOTE_EXCEP' ##NO_TEXT.
  constants GC_PARAM_UNIT_G type ZEWM_DE_BASE_PARAMS_KEYNAM value 'UNIT_G' ##NO_TEXT.
  constants GC_PARAM_UPD_GUIA_ECC type ZEWM_DE_BASE_PARAMS_KEYNAM value 'UPD_GUIA_ECC' ##NO_TEXT.
  constants GC_PARAM_WORKCENTER type ZEWM_DE_BASE_PARAMS_KEYNAM value 'WORKCENTER' ##NO_TEXT.
  constants GC_ENH_RF_SHORT_PICK type ZEWM_DE_BASE_PARAMS_KEYENH value 'RF_SHORT_PICK' ##NO_TEXT.
  constants GC_PARAM_SHORT_PICK_PROCTY type ZEWM_DE_BASE_PARAMS_KEYNAM value 'SHORT_PICK_PROCTY' ##NO_TEXT.
  constants GC_FILTER_ST_0210 type ZEWM_DE_BASE_PARAMS_FILTER value '0210' ##NO_TEXT.
  constants GC_FILTER_ST_0230 type ZEWM_DE_BASE_PARAMS_FILTER value '0230' ##NO_TEXT.
  constants GC_ENH_BADI_ST_REMOV_STRA_REPL type ZEWM_DE_BASE_PARAMS_KEYENH value 'SRSRWU' ##NO_TEXT.
  constants GC_PARAM_GRP_PROD_BULK type ZEWM_DE_BASE_PARAMS_KEYNAM value 'PRODUCT_GRP_BULK' ##NO_TEXT.
  constants GC_ENH_RF_VLTYP_PICKING type ZEWM_DE_BASE_PARAMS_KEYNAM value 'RF_VERF_CTRL' ##NO_TEXT.
  constants GC_PARAM_VLTYP_PICKING type ZEWM_DE_BASE_PARAMS_KEYNAM value 'LGPLA_VERFCTL' ##NO_TEXT.
  constants GC_ENH_RF_CHPM type ZEWM_DE_BASE_PARAMS_KEYNAM value 'CH_PMAT_RF' ##NO_TEXT.
  constants GC_ENH_COND_BADI type ZEWM_DE_BASE_PARAMS_KEYENH value 'COND_BADI' ##NO_TEXT.
  constants GC_PARAM_LOGICAL_TRANS type ZEWM_DE_BASE_PARAMS_KEYNAM value 'LOG_TRANS' ##NO_TEXT.
  constants GC_PARAM_TRANS_CODE type ZEWM_DE_BASE_PARAMS_KEYNAM value 'TRANS_CODE' ##NO_TEXT.
  constants GC_ENH_CIF_BP type ZEWM_DE_BASE_PARAMS_KEYENH value 'CIF_BP' ##NO_TEXT.
  constants GC_PARAM_NR_BP type ZEWM_DE_BASE_PARAMS_KEYNAM value 'NR_BP' ##NO_TEXT.
  constants GC_ENH_SMARTFORMS type ZEWM_DE_BASE_PARAMS_KEYENH value 'SMARTFORMS' ##NO_TEXT.
  constants GC_PARAM_MATGR type ZEWM_DE_BASE_PARAMS_KEYNAM value 'MATGR' ##NO_TEXT.
  constants GC_ENH_PRINTLOGO type ZEWM_DE_BASE_PARAMS_KEYENH value 'PRINTLOGO' ##NO_TEXT.
  constants GC_PARAM_LOGO type ZEWM_DE_BASE_PARAMS_KEYNAM value 'LOGO' ##NO_TEXT.
  constants GC_PARAM_PRINTER type ZEWM_DE_BASE_PARAMS_KEYNAM value 'PRINTER' ##NO_TEXT.
  constants GC_ENH_RF_PRINT type ZEWM_DE_BASE_PARAMS_KEYENH value 'PRINT' ##NO_TEXT.
  constants GC_PARAM_WHMATGR type ZEWM_DE_BASE_PARAMS_KEYNAM value 'WHMATGR' ##NO_TEXT.
  constants GC_ENH_WT_RESORT type ZEWM_DE_BASE_PARAMS_KEYENH value 'RSWTSQ' ##NO_TEXT.
  constants GC_PARAM_WT_DESCEN type ZEWM_DE_BASE_PARAMS_KEYNAM value 'WTDESC' ##NO_TEXT.
  constants GC_ENH_WCR_FILTERS type ZEWM_DE_BASE_PARAMS_KEYENH value 'WOCRFL' ##NO_TEXT.
  constants GC_ENH_CLOSE_HU type ZEWM_DE_BASE_PARAMS_KEYENH value 'CLOSEHU' ##NO_TEXT.
  constants GC_ENH_ADJUST_CAT type ZEWM_DE_BASE_PARAMS_KEYENH value 'ADJUSTMENT_CAT' ##NO_TEXT.
  constants GC_PARAM_STOCK_TYPE type ZEWM_DE_BASE_PARAMS_KEYNAM value 'STOCK_TYPE' ##NO_TEXT.
  constants GC_PARAM_OWNER type ZEWM_DE_BASE_PARAMS_KEYNAM value 'OWNER' ##NO_TEXT.
  constants GC_ENH_RF_CREATE_TU type ZEWM_DE_BASE_PARAMS_KEYENH value 'RF_CREATE_TU' ##NO_TEXT.
  constants GC_ENH_RF_CLOSE_TU type ZEWM_DE_BASE_PARAMS_KEYENH value 'RF_CLOSE_TU' ##NO_TEXT.
  constants GC_PARAM_DIST_LIST type ZEWM_DE_BASE_PARAMS_KEYNAM value 'DIST_LIST' ##NO_TEXT.
endinterface.
